apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-dashboard

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

# Common labels for all resources
commonLabels:
  app: weather-dashboard
  managed-by: kustomize

# Images to patch (useful for different environments)
images:
  - name: weather-dashboard
    newTag: latest

# ConfigMap generator (alternative to configmap.yaml)
# configMapGenerator:
#   - name: weather-dashboard-config
#     literals:
#       - FLASK_ENV=production
#       - LOG_LEVEL=INFO

# Secret generator (alternative to secret.yaml)
# secretGenerator:
#   - name: weather-dashboard-secrets
#     literals:
#       - WEATHER_API_KEY=your-api-key-here
