apiVersion: v1
kind: Secret
metadata:
  name: weather-dashboard-secrets
  namespace: weather-dashboard
  labels:
    app: weather-dashboard
type: Opaque
data:
  # Base64 encoded values - replace with your actual API key
  # echo -n "your-api-key" | base64
  WEATHER_API_KEY: "your-base64-encoded-api-key-here"
  # Add other sensitive configuration here
  # FLASK_SECRET_KEY: "your-base64-encoded-secret-key-here"
