[testpypi]
username = "__token__"
password = "pypi-AgENdGVzdC5weXBpLm9yZwIkN2YxM2I5MzktOWI0ZC00ODIyLTg3MmQtMmEyZGU0YWRkNjU2AAIqWzMsIjYzZGFlY2ExLTIzZjItNDYzZS1hZDI4LTA1YTYzNmU5NTllYiJdAAAGINKKhmkGJcWoZQDCVEXVM-mJsYnVxFmanAhbEQQ-Ud_L"
